#!/bin/sh
# Sentinel Shield — maturity / adoption report (v1.8.0).
#
# ADDITIVE, offline. Emits the current scanner maturity matrix as markdown (default) or JSON.
# This is a REPORT of the canonical state in docs/product-status.md + main-gate-live-evidence.md;
# it changes nothing. Keep it in sync when a maturity label changes (guarded by self-test v180).
#
# Usage: sh scripts/maturity-report.sh [--format md|json]
set -eu
FORMAT="md"
while [ $# -gt 0 ]; do case "$1" in
  --format) FORMAT="${2:?--format requires a value}"; shift 2 ;;
  -h|--help) echo "Usage: maturity-report.sh [--format md|json]"; exit 0 ;;
  *) echo "[sentinel-shield][error] maturity-report: unknown argument: $1" >&2; exit 2 ;;
esac; done

# tool|category|maturity|evidence_run|artifact|caveat|default|gating
ROWS='engine|core|proven|self-test (this repo CI)|security-summary.json|deterministic|yes|gating
Deptrac|architecture|live-validated|27633798174 (silver-potato)|deptrac.json|binary severity (count)|opt-in|gating
OWASP Dependency-Check|dependencies|live-validated|27530386965 / 27573703800|dependency-check.json|coarse severity|main|gating
CodeQL|SAST|live-validated|27214865086|codeql.json|SARIF level->severity (coarse)|main|gating
OSV-Scanner|dependencies|live-validated|27214865086|osv-scanner.json|severity coarse (all->high)|main|gating
Trivy-fs|dependencies|live-validated|27214865086|trivy.json|fs-mode only|main|gating
Syft (SBOM)|sbom|live-validated|27214865086|sbom.spdx.json|presence/validity only|main|gating
Grype|dependencies|live-validated|27239206382|grype.json|severity-mapped|main|gating
Dockle|container|live-validated|27239206382|dockle.json|built-image only|nightly|gating
Checkov|iac|ci-validated (evidence-fixture)|27636439883|checkov.json|engineered findings; NOT live-validated|if IaC|gating
Terrascan|iac|ci-validated (evidence-fixture)|27636439883|terrascan.json|no hcloud policies; NOT live-validated|if IaC|gating
Conftest|iac|ci-validated (evidence-fixture)|27636439883|conftest-report.json|namespace/plan-JSON; NOT live-validated|if IaC|gating
ZAP / Nuclei|dast|manual|—|zap.json / nuclei.json|target allowlist + approval|off|manual
Claude Code review / Kuzushi|ai|non-gating|—|ai-security-review.json|non-deterministic; advisory|off|non-gating
Scorecard / TruffleHog / Trivy-image|misc|experimental|—|*.json|coarse / nightly|nightly|advisory'

if [ "$FORMAT" = "json" ]; then
  printf '{"generated_by":"scripts/maturity-report.sh","release":"v1.8.0","tools":['
  first=1; printf '%s\n' "$ROWS" | while IFS='|' read -r t c m r a v d g; do
    [ "$first" = 1 ] || printf ','; first=0
    printf '{"tool":"%s","category":"%s","maturity":"%s","evidence_run":"%s","artifact":"%s","caveat":"%s","default":"%s","gating":"%s"}' \
      "$t" "$c" "$m" "$r" "$a" "$v" "$d" "$g"
  done
  printf ']}\n'
elif [ "$FORMAT" = "md" ]; then
  echo "# Sentinel Shield — Scanner Maturity Report (v1.8.0)"
  echo
  echo "Generated by \`scripts/maturity-report.sh\`. Canonical source: \`docs/product-status.md\` +"
  echo "\`docs/main-gate-live-evidence.md\`. **IaC is \`ci-validated (evidence-fixture)\`, NOT \`live-validated\`.**"
  echo
  echo "| Tool | Category | Maturity | Evidence run | Artifact | Caveat | Default | Gating |"
  echo "|---|---|---|---|---|---|---|---|"
  printf '%s\n' "$ROWS" | while IFS='|' read -r t c m r a v d g; do
    printf '| %s | %s | %s | %s | %s | %s | %s | %s |\n' "$t" "$c" "$m" "$r" "$a" "$v" "$d" "$g"
  done
else
  echo "[sentinel-shield][error] maturity-report: --format must be md or json" >&2; exit 2
fi
exit 0
